[build]
  # Use npm ci then run the project's build script to ensure a clean install
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  # Hint to Netlify about Node version to use during build (Netlify may respect engines too)
  NODE_VERSION = "20"
